apiVersion: apps/v1              # apps: is group and deployment is under apps group
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns 
  labels:
    app: nginx
spec:                            # deployment specification
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

