apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: nginx-ns
  
spec:
  selector:
    app: nginx                       # this lable is your deployment metadata label
  ports:
    - protocol: TCP
      port: 80                       # cluster port / host port / service port
      targetPort: 9376               # target port is your pod port means cointainer port

      

